# Generated by Django 4.0.2 on 2022-09-03 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('workshop_link', models.URLField()),
                ('is_online', models.BooleanField()),
                ('is_in_person', models.BooleanField()),
                ('date_and_time', models.DateTimeField()),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organiser_workshops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
