# Generated by Django 4.0.2 on 2022-08-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='organiser',
            field=models.CharField(max_length=100),
        ),
    ]
