# Generated by Django 4.0.2 on 2022-09-10 04:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_is_hybrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='topics',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('Python', 'Python'), ('Django', 'Django'), ('DRF', 'DRF'), ('React', 'React'), ('PHP', 'PHP'), ('AWS', 'AWS'), ('Testing', 'Testing')], max_length=48),
        ),
    ]
