# Generated by Django 4.0.2 on 2022-08-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_workshop_organiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='topics',
        ),
    ]
