# Generated by Django 4.0.2 on 2022-09-10 05:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshop_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='experience_level',
            field=models.CharField(choices=[('EL', 'Entry-level'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], default='EL', max_length=20),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='topics',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('Python', 'Python'), ('Django', 'Django'), ('DRF', 'DRF'), ('React', 'React'), ('PHP', 'PHP'), ('AWS', 'AWS'), ('Testing', 'Testing'), ('Other', 'Other')], max_length=54),
        ),
    ]
