# Generated by Django 4.0.2 on 2022-09-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshop_experience_level_alter_workshop_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='is_hybrid',
        ),
        migrations.AddField(
            model_name='workshop',
            name='physical_location',
            field=models.CharField(default='Brisbane', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='experience_level',
            field=models.CharField(choices=[('EL', 'Entry-level'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], default='Entry-level', max_length=20),
        ),
    ]
