# Generated by Django 4.0.2 on 2022-09-01 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0005_workshop_organiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='organiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organiser_workshops', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
