# Generated by Django 4.0.2 on 2022-06-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('is_open', models.BooleanField()),
                ('date_created', models.DateTimeField()),
                ('owner', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('bris', 'Brisbane floods 2022'), ('canb', 'Canberra fires 2021'), ('lism', 'Lismore Floods 2022')], max_length=200)),
            ],
        ),
    ]
