# Generated by Django 4.0.2 on 2022-06-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
    ]
